services:
  kasa-collector:
    container_name: kasa-collector
    environment:
      TZ: America/Chicago
      KASA_COLLECTOR_COLLECT_INTERVAL: 5
      KASA_COLLECTOR_DEBUG: "false"
      KASA_COLLECTOR_DEBUG_CURL: "false"
      KASA_COLLECTOR_DEBUG_SLEEPING: "false"
      KASA_COLLECTOR_DEVICE_HOST: kasa-device01.lux4rd0.com,kasa-device02.lux4rd0.com,kasa-device03.lux4rd0.com
      KASA_COLLECTOR_HOST_HOSTNAME: kasa-collector.lux4rd0.com
      KASA_COLLECTOR_INFLUXDB_PASSWORD: none
      KASA_COLLECTOR_INFLUXDB_URL: http://influxdb01.lux4rd0.com:8086/write?db=kasa
      KASA_COLLECTOR_INFLUXDB_USERNAME: none
    image: lux4rd0/kasa-collector:latest
    restart: always
version: '3.3'
